apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "strimzi-topic-operator.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "strimzi-topic-operator.name" . }}
    chart: {{ template "strimzi-topic-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "strimzi-topic-operator.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "strimzi-topic-operator.name" . }}
        release: {{ .Release.Name }}      
    spec:
      securityContext:
        runAsUser: 999   
      serviceAccountName: {{ template "strimzi-topic-operator.fullname" . }}
      containers:
        - name: {{ template "strimzi-topic-operator.name" . }}
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          env:
            - name: STRIMZI_CONFIGMAP_LABELS
              value: "strimzi.io/kind=topic"
            - name: STRIMZI_KAFKA_BOOTSTRAP_SERVERS
              value: {{ template "strimzi-topic-operator.kafka.bootstrapServers" . }}
            - name: STRIMZI_ZOOKEEPER_CONNECT
              value: {{ template "strimzi-topic-operator.cp-zookeeper.service-name" . }}
            - name: STRIMZI_ZOOKEEPER_SESSION_TIMEOUT_MS
              value: "20000"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "-1"
            - name: STRIMZI_TOPIC_METADATA_MAX_ATTEMPTS
              value: "6"
            - name: STRIMZI_LOG_LEVEL
              value: INFO
            - name: STRIMZI_TLS_ENABLED
              value: "false"
            - name: STRIMZI_NAMESPACE
              value: {{ .Values.namespace }},kube-public
          resources:
            limits:
              memory: 96Mi
              cpu: 100m
            requests:
              memory: 96Mi
              cpu: 100m
  strategy:
    type: Recreate
