---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "strimzi-topic-operator.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "strimzi-topic-operator.name" . }}
    chart: {{ template "strimzi-topic-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "strimzi-topic-operator.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "strimzi-topic-operator.name" . }}
    chart: {{ template "strimzi-topic-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - "kafka.strimzi.io"
  resources:
  - kafkatopics
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "strimzi-topic-operator.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "strimzi-topic-operator.name" . }}
    chart: {{ template "strimzi-topic-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: {{ template "strimzi-topic-operator.fullname" . }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "strimzi-topic-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
