apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-control-center.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "cp-control-center.name" . }}
    chart: {{ template "cp-control-center.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: control-center
      port: {{ .Values.servicePort }}
  selector:
    app: {{ template "cp-control-center.name" . }}
    release: {{ .Release.Name }}
